### ISSUE TITLE
is-array? throws exception on nil in clj

### ISSUE THREAD

**Issue by timothypratley** [tonsky/persistent-sorted-set#4]
A minor annoyance that causes an downstream issue:
`(d/conn-from-datoms (d/datoms @*conn :eavt) schema)` will fail on an empty database.
This is the recommended way to update a schema from DataScript documentation.
This in turn can be easily worked around by only using `conn-from-datoms` for non-nil.

However type checks typically shouldn't throw exceptions, so submitting a patch.

**Comment by tonsky** [comment]
Thank you! Just pushed DataScript 1.2.1

**Comment by timothypratley** [comment]
Thank you :)
